DROP DATABASE IF EXISTS cafe_db;
CREATE DATABASE cafe_db;

USE cafe_db;

CREATE TABLE products (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(5, 2) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE couriers (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);
